### ISSUE TITLE
third_party/r3d3/pred/samples for test

### ISSUE THREAD

**Issue by yangshunDragon** [Barrybarry-Smith/Driv3R#2]
hello, thanks for sharing!

Could you please also provide the third_party/r3d3/pred/samples for testing?
BTW, do you have a time schedule to support Waymo, KITTI, and DDAD datasets?

**Comment by Barrybarry-Smith** [comment]
Thank you for your attention. 

The depth results in third_party/r3d3/pred/samples are only required for training. If you only need to evaluate the model, you can simply comment out the corresponding lines. Besides, this folder is quite large (>200GB), so it might be more convenient to follow the R3D3 instructions to generate the depth predictions instead.

As for the additional datasets, we will add the preprocessing file to the codebase once finished.
