### ISSUE TITLE
Why LiDAR shift is needed in evaluation for visualizing?

### ISSUE THREAD

**Issue by synsin0** [Barrybarry-Smith/Driv3R#4]
Thanks for your great work. I'd like to ask that why the evaluation and visualization needs shift from LiDAR? Is it from the relative depth estimation of Dust3R? Or the LiDAR is actually not needed in evaluation (the model is by itself scale and shift aware)?

**Comment by synsin0** [comment]
I want to save a visual point cloud so that it matches the lidar point cloud well. I tried to use align_and_vis.py but the point cloud of each frame doesn't look like a lidar point cloud.
I see that shift_z compensation is needed in the eval.py, as well as the operation of ICP registration GT and PRED to match GT as much as possible, is this because Dust3r estimates the inaccurate pose? I would like to ask you for some guidance.

**Comment by Barrybarry-Smith** [comment]
Thank you for your attention. In the evaluation, the predicted point cloud has not yet been transformed to the scale of world coordinate system, thus we need the scale and shift to align GT and predicted point, but in visualization they are not used. 

Besides, I can not get the point that "the point cloud of each frame doesn't look like a lidar point cloud". Do you mean that the LiDAR points are sparse while predicted points are dense? Please elaborate.

**Comment by synsin0** [comment]
sorry for my inaccurate expressions. I'd like to ask whether both scale and shift are not estimated by driv3r?  In visualization script, you use a fixed scale 120, does it apply to the  scale of the real world?

**Comment by Barrybarry-Smith** [comment]
I get the point. I hope the following explanation can address your concern.
(1) Driv3R is DUSt3R-based, so the inference result can not reflect the scale and shift of real world, and we need to use the align script to transform all points to world coordinate system.
(2) If you want to apply visualization on more generalizable cases, I recommend to use the average median GT depth as the arg.scale, the value 120 is solely our calculation that fits for NuScenes.
If you have any problem, feel free to let me know.

**Comment by synsin0** [comment]
I'd like to summarize my understanding. If I want to save a 4d image point that is very similar to the corresponding lidar point clouds as described in table.2. I need to follow the procedure of eval.py and transform the predicted point cloud to the lidar point scale. Please check if I am right. Thanks again for your help!

**Comment by Barrybarry-Smith** [comment]
One correction. To get the result in Table 2, you do not have to transform the predicted points to the scale of LiDAR points, you only need to do so for visualization in the real world coordinate system. For depth evaluation, just transform the predicted and GT points to a uniform coordinate system.

**Comment by synsin0** [comment]
I find that the predicted points is transformed to LiDAR scale in Regr3D_t_ScaleInv.get_all_pts3d_t() in eval.py. I mean the evaluation on points but not depth.
I am confused why the predicted coordinate system is not uniform with the GT points (the ICP process in eval.py). Is it related to the pose estimation process in Dust3R? 
 I'm a new comer of 3D geometry.

**Comment by Barrybarry-Smith** [comment]
The predicted points are in the first frame's coordinate system originally, but they do not reflect the scale of real world (please see DUSt3R paper for details). To evaluate, you need to transform both predicted and GT points to a uniform coordinate system (that is what we do before line 207 in eval.py). To visualize in the world coordinate system, you need to transform the predicted points to align the real world scale (that is what we do before line 162 in align_and_vis.py).

**Comment by synsin0** [comment]
Thanks for your answering! I will take a closer look at the related papers and codes.
